<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>Capcap</AssemblyName>
    <RootNamespace>Capcap</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Vortice.DXGI" Version="1.6.0" />
    <PackageReference Include="Vortice.Direct3D11" Version="1.6.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Sounds\click.wav" LogicalName="Capcap.Sounds.click.wav" />
    <EmbeddedResource Include="Sounds\typing.wav" LogicalName="Capcap.Sounds.typing.wav" />
    <EmbeddedResource Include="Sounds\scroll.wav" LogicalName="Capcap.Sounds.scroll.wav" />
  </ItemGroup>

</Project>
